### ISSUE TITLE
Make TuringMachine.c portable

### ISSUE THREAD

**Issue by robertg** [yedhukrishnan/turing-machine#1]
`stdio_ext.h` is not portable.

I believe the following will do the trick:

```
-                       __fpurge(stdin);
+                        {
+                              int c;
+                              while((c = getchar()) != '\n' && c != EOF);
+                        }
```

However I still have one [lingering question](https://news.ycombinator.com/item?id=9480304): How do you use SampleMultiplication? How does the input string look like, as my attempts get a `SEGFAULT`.

**Comment by yedhukrishnan** [comment]
Thanks! I will resolve this issue. If you would like to give a pull request, you are most welcome :)

Let me run the program once (It's been a long time since I've touched the code). Then I'll tell how to run the program with SampleMultiplication.

**Comment by yedhukrishnan** [comment]
@robertg Sorry for the late response. I've made some changes and tried it in both OSX and Linux. I've also removed the writing output to file part from the program.

Also, you can use the sample multiplication file as follows:

```
./turing_machine sample_multiplication 110111
```

Try this, you are free to skip the last part (110111). The segmentation fault was happening due to some error in file writing part. Now it is fixed.
